Refactored RPM build process; added replacer plugin

diff --git a/languagetool-rpm-package/src/main/resources/ltserver b/languagetool-rpm-package/src/main/resources/ltserver
--- a/languagetool-rpm-package/src/main/resources/ltserver
+++ b/languagetool-rpm-package/src/main/resources/ltserver
@@ -2,12 +2,25 @@
 
 # This script creates classpath and starts LT server
 
-# Source shell variables for server
-. /etc/languagetool/lt.conf
+# Check if config file exists
+if [ -f /etc/languagetool/lt.conf ]; then
+	# Source shell variables for server
+	. /etc/languagetool/lt.conf
+else
+	echo "Configuration file /etc/languagetool/lt.conf was not found, aborting ..."
+	exit 1
+fi
+[ "${LT_DEBUG}" -eq 1 ] && set -x
+
+# Check if LT_HOME was set
+if [ -z ${LT_HOME} ]; then
+	echo "Environment variable LT_HOME, root directory of LT installation, must be set. Aborting ..."
+	exit 1
+fi
 
 # Check if LT_JAVA_HOME was set
 if [ -z ${LT_JAVA_HOME} ]; then
-	echo "Environment variable LT_JAVA_HOME, pointing to Java 8+ executable, must be set."
+	echo "Environment variable LT_JAVA_HOME, pointing to Java 8+ installation, must be set. Aborting ..."
 	exit 1
 fi
 
@@ -46,13 +59,33 @@ check_status() {
 # Create options
 function build_lt_options() {
 	LT_OPTIONS="${LT_JAVA_OPTS} -cp ${LT_CP}"
-	if [ ! -z "${LT_SECURE_SERVER}" -a "${LT_SECURE_SERVER}" -eq 1 ]; then
-		LT_OPTIONS="${LT_OPTIONS} org.languagetool.server.HTTPSServer"
+	if [ ! -z "${LT_SRV_SECURE}" ]; then
+		if [ "${LT_SRV_SECURE}" -eq 1 ]; then
+			LT_OPTIONS="${LT_OPTIONS} org.languagetool.server.HTTPSServer"
+		else
+			LT_OPTIONS="${LT_OPTIONS} org.languagetool.server.HTTPServer"
+		fi
 	else
 		LT_OPTIONS="${LT_OPTIONS} org.languagetool.server.HTTPServer"
 	fi
 	LT_OPTIONS="${LT_OPTIONS} --config /etc/languagetool/server.properties"
 	LT_OPTIONS="${LT_OPTIONS} --port ${LT_PORT}"
+	if [ ! -z "${LT_SRV_PUBLIC}" ]; then
+		if [ "${LT_SRV_PUBLIC}" -eq 1 ]; then
+			LT_OPTIONS="${LT_OPTIONS} --public"
+		fi
+	fi
+	if [ ! -z "${LT_SRV_VERBOSE}" ]; then
+		if [ "${LT_SRV_VERBOSE}" -eq 1 ]; then
+			LT_OPTIONS="${LT_OPTIONS} --verbose"
+		fi
+	fi
+	if [ ! -z "${LT_SRV_LANG_MODEL}" ]; then
+		LT_OPTIONS="${LT_OPTIONS} --languageModel ${LT_SRV_LANG_MODEL}"
+	fi
+	if [ ! -z "${LT_SRV_ALLOW_ORIGIN}" ]; then
+		LT_OPTIONS="${LT_OPTIONS} --allow-origin ${LT_SRV_ALLOW_ORIGIN}"
+	fi
 }
 
 # Starts the application
@@ -63,24 +96,35 @@ start() {
   pid=$(check_status)
 
   if [ $pid -ne 0 ] ; then
-    echo "${LT_NAME} is already running (PID ${pid})."
+    echo "${LT_SRV_NAME} is already running (PID ${pid})."
     exit 1
   fi
   
-  create_lt_class_path
- 
+  create_lt_class_path 
   build_lt_options
   
-  # Check what server will be started, secure or insecure
-  if [ ! -z "${LT_SECURE_SERVER}" -a "${LT_SECURE_SERVER}" -eq 1 ]; then
-    echo -n "Starting HTTPS ${LT_NAME} ... "
-  else
-    echo -n "Starting HTTP ${LT_NAME} ... "
+  if [ ! -f "${LT_LOG_FILE}" ]; then
+    > "${LT_LOG_FILE}"
   fi
- 
+  
+  # Check what server will be started, secure or insecure
+  TSTMP=`date`
+  echo ${TSTMP} "===========" >> ${LT_LOG_FILE}
+  
+  if [ ! -z "${LT_SRV_SECURE}"  ]; then
+    echo -n "Starting HTTPS ${LT_SRV_NAME} ... "
+  else
+    echo -n "Starting HTTP ${LT_SRV_NAME} ... "
+  fi
+
+  if [ "${LT_SRV_ALLOW_ORIGIN}" == "*" ]; then
+      # Trick to pass asterisk as argument to "--allow-origin" option
+	  set -o noglob
+  fi
   # Redirects default and error output to a log file
   ${LT_JAVA_HOME}/bin/java ${LT_OPTIONS} >> ${LT_LOG_FILE} 2>&1 &
   echo $! > ${LT_PID_FILE}
+  set +o noglob
   echo "OK"
 }
  
@@ -91,12 +135,15 @@ stop() {
   pid=$(check_status)
  
   if [ $pid -eq 0 ] ; then
-    echo "${LT_NAME} is already stopped."
+    echo "${LT_SRV_NAME} is already stopped."
+    if [ -f ${LT_PID_FILE} ]; then
+      rm -f ${LT_PID_FILE}
+    fi
     exit 1
   fi
  
   # Kills the application process
-  echo -n "Stopping ${LT_NAME} ..."
+  echo -n "Stopping ${LT_SRV_NAME} ..."
   kill -15 $pid
   rm -f ${LT_PID_FILE}
   echo "OK"
@@ -110,9 +157,9 @@ status() {
 
   # If the PID was returned means the application is running
   if [ ${pid} -ne 0 ] ; then
-    echo "${LT_NAME} is running (PID ${pid})."
+    echo "${LT_SRV_NAME} is running (PID ${pid})."
   else
-    echo "${LT_NAME} is stopped."
+    echo "${LT_SRV_NAME} is stopped."
   fi
  
 }
